 <!DOCTYPE html>
<html>
<head>
<style>
body {
  
 font-size:15px;
 
}

table {
  border-collapse: collapse;
   border-radius:15px;
}

.topbott{
  border-top:1px solid black;
  border-bottom:1px solid black;
}
.bott{
  border-bottom:1px solid black;
}
</style>
</head>
<body >



<table width="100%">
<tbody>
<tr>
<td colspan="7" style="text-align:center;font-size:20px;font-weight:800;"><strong>E-WAY BILL SYSTEM</strong></td>
</tr>
<tr>
<td colspan="7"style="text-align:center;padding-top:20px;"><strong>e-Way Bill</strong></td>
</tr>
<tr>
<?php $image_path = '/img/barcode.png'; ?>
      
<td colspan="7"><center> <img src="{{ public_path() . $image_path }}" width="120" height="120" alt="" style="margin-top:20px;"/></center></td>
</tr>
<tr >
<td colspan="2" style="padding-top:20px;">E-Way Bill No</td>
<td colspan="5" style="padding-top:20px;">: 311177453060</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">E-Way Bill Date</td>
<td colspan="5" style="padding-top:10px;">: 2020-03-04 11:28:17</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Generated By</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Valid From</td>
<td colspan="5" style="padding-top:10px;">: 2020-03-04 11:28:17</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;padding-bottom:15px;">Valid Until</td>
<td colspan="5" style="padding-top:10px;padding-bottom:15px;">: 2020-03-10 11:28:17</td>
</tr>
<tr>
<td colspan="7" style="padding-top:10px;border-top:1px solid black;"><strong>Part - A</strong></td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">GSTIN of Supplier</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Place of Dispatch</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">GSTIN of Recipient</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Place of Delivery</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Document No</td>
<td colspan="5" style="padding-top:10px;">: Test001</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Document Date</td>
<td colspan="5" style="padding-top:10px;">: 02.01.2020</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Transaction Type</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Value of Goods</td>
<td colspan="5" style="padding-top:10px;">: 10761.6</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">HSN Code</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;">Reason For Transportation</td>
<td colspan="5" style="padding-top:10px;">&nbsp;</td>
</tr>
<tr>
<td colspan="2" style="padding-top:10px;padding-bottom:15px;">Transporter</td>
<td colspan="5" style="padding-top:10px;padding-bottom:15px;">: null</td>
</tr>
<tr>
<td colspan="7" style="padding-top:10px;border-top:1px solid black;padding-bottom:10px;"><strong>Part - B</strong></td>
</tr>
<tr >
<td style="text-align:center; border-left:1px solid black;padding:30px 0px;" class="topbott"><strong>Mode</strong></td>
<td style="text-align:center;padding:30px 0px;" class="topbott"><strong>Vehicle / Trans<br>Doc No & Dt.</strong></td>
<td style="text-align:center;padding:30px 0px;" class="topbott"><strong>From</strong></td>
<td style="text-align:center;padding:30px 0px;" class="topbott"><strong>Entered Date</strong></td>
<td style="text-align:center;padding:30px 0px;" class="topbott"><strong>Entered by</strong></td>
<td style="text-align:center;padding:30px 0px;" class="topbott"><strong>CEWB No.<br>(if any)</strong></td>
<td style="text-align:center;padding:30px 0px;border-right:1px solid black;" class="topbott"><strong>Multi Veh.info<br>(if any)</strong></td>
</tr>
<tr>
<td style="text-align:center;padding:30px 0px;border-left:1px solid black;"class="bott">Road</td>
<td style="text-align:center;padding:30px 0px;" class="bott">Chennai</td>
<td colspan="5" style="padding:30px 0px;border-right:1px solid black;" class="bott">&nbsp;</td>
</tr>
<tr>
<td colspan="7" style="padding-top:20px;border-bottom:1px solid black;">&nbsp;</td>
</tr>
</tbody>
</table>

</body>
</html>